dist: xenial
language: cpp
compiler: g++
addons:
  yum:
    packages:
    - libboost-test-dev
    - libspdlog-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -f -T helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.rpm -uandreykoloskov:$BINTRAY_API_KEY "https://api.bintray.com/content/andreykoloskov/cpp/homework/$TRAVIS_BUILD_NUMBER/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.rpm;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
